project:
  type: website
  output-dir: docs
  render:
    - example.qmd
    - about.qmd
    
toc: true
number-sections: true

format:
  html:
    toc: true
    self-contained: TRUE
code-fold: true
editor: visual
theme: darkly
bibliography: references.bib
csl: harvard-deakin-university.csl

website:
  navbar:
    background: primary
    left:
      - icon: house
        href: example.qmd
        text: Home
      - href: http://ziemann-lab.net
        text: Lab Webpage
      - href: about.qmd
        text: About us
    right: 
      - icon: github
        href: https://github.com/markziemann/quarto_example
      - icon: twitter
        href: https://twitter.com/mdziemann